"""G-code Generation Engine for 2D Powder-Dispensing Gantry."""

from __future__ import annotations
import math
from dataclasses import dataclass
from typing import List, Optional, Tuple, Dict, Any
from .geometry import BaseShape, ToolpathSegment, Point2D, DispenseDotShape


@dataclass
class GCodeConfig:
    travel_feedrate: float = 3000.0       # mm/min for G0 rapid moves
    default_dispense_feedrate: float = 500.0 # mm/min for G1 dispensing moves
    default_motor_pwm: int = 255          # 0-255 PWM for M106
    pre_dispense_dwell_ms: int = 50       # G4 P dwell in ms
    post_dispense_dwell_ms: int = 50      # G4 P dwell in ms
    home_on_start: bool = True
    return_to_origin_on_end: bool = True
    startup_gcode: str = "G21 ; mm units\nG90 ; Absolute coordinates\nM107 ; Powder motor OFF\nG28 XY ; Home XY"
    ending_gcode: str = "M107 ; Powder motor OFF\nG0 X0 Y0 ; Return to origin\nM84 ; Disable steppers"
    decimal_places: int = 3
    safe_z_command: str = ""              # Optional Z retraction if 3D gantry configured


@dataclass
class GCodeStats:
    total_lines: int = 0
    total_travel_dist_mm: float = 0.0
    total_dispense_dist_mm: float = 0.0
    estimated_time_sec: float = 0.0
    shape_count: int = 0


class GCodeGenerator:
    """Compiles vector shapes and fill paths into clean Marlin G-code."""

    def __init__(self, config: Optional[GCodeConfig] = None):
        self.config = config or GCodeConfig()

    def generate(
        self,
        shapes: List[BaseShape],
        dry_run: bool = False
    ) -> Tuple[str, GCodeStats]:
        """
        Generates full G-code program from a list of shapes.
        
        Args:
            shapes: List of BaseShape vector objects.
            dry_run: If True, M106 motor ON commands are replaced/commented out.
            
        Returns:
            Tuple of (gcode_string, statistics).
        """
        lines: List[str] = []
        stats = GCodeStats(shape_count=len(shapes))
        current_pos: Optional[Point2D] = Point2D(0, 0)
        current_feedrate: Optional[float] = None
        dec = self.config.decimal_places

        # Header
        lines.append("; ===================================================")
        lines.append("; Generated by DPW 2D Powder-Dispensing Gantry Controller")
        lines.append(f"; Mode: {'DRY RUN (Motor Disabled)' if dry_run else 'ACTIVE DISPENSE'}")
        lines.append(f"; Shapes count: {len(shapes)}")
        lines.append("; ===================================================")
        lines.append("")

        # Startup script
        for raw_line in self.config.startup_gcode.splitlines():
            s = raw_line.strip()
            if s:
                lines.append(s)
        
        # Set initial rapid travel feedrate
        lines.append(f"G0 F{self.config.travel_feedrate:.1f}")
        current_feedrate = self.config.travel_feedrate
        lines.append("")

        # Process each visible shape
        for shape_idx, shape in enumerate(shapes):
            if not shape.is_visible:
                continue

            lines.append(f"; --- Shape [{shape_idx + 1}/{len(shapes)}]: {shape.name} ({shape.shape_type.value}) ---")
            segments = shape.generate_toolpaths()
            pwm = shape.motor_pwm if shape.motor_pwm is not None else self.config.default_motor_pwm
            feed = shape.dispense_feedrate if shape.dispense_feedrate is not None else self.config.default_dispense_feedrate

            for seg_idx, seg in enumerate(segments):
                if not seg.points:
                    continue

                # 1. Rapid move (G0) to segment start point
                start_pt = seg.points[0]
                if current_pos is None or current_pos.distance_to(start_pt) > 1e-4:
                    travel_dist = current_pos.distance_to(start_pt) if current_pos else 0.0
                    stats.total_travel_dist_mm += travel_dist
                    stats.estimated_time_sec += (travel_dist / (self.config.travel_feedrate / 60.0))
                    
                    # Ensure motor is OFF during travel
                    lines.append("M107 ; Motor OFF for rapid move")
                    lines.append(f"G0 X{start_pt.x:.{dec}f} Y{start_pt.y:.{dec}f} F{self.config.travel_feedrate:.1f}")
                    current_pos = Point2D(start_pt.x, start_pt.y)
                    current_feedrate = self.config.travel_feedrate

                # Special case: Dispense Dot (dwell at single point)
                if isinstance(shape, DispenseDotShape) or len(seg.points) == 1:
                    dwell = seg.dwell_ms if seg.dwell_ms > 0 else 500
                    if dry_run:
                        lines.append(f"; [DRY RUN] M106 S{pwm} (Dispense Dot)")
                    else:
                        lines.append(f"M106 S{pwm} ; Dispenser ON (PWM {pwm})")
                    
                    lines.append(f"G4 P{dwell} ; Dispense Dwell {dwell}ms")
                    stats.estimated_time_sec += (dwell / 1000.0)
                    lines.append("M107 ; Dispenser OFF")
                    continue

                # 2. Turn on powder vibration motor
                if seg.is_dispense:
                    seg_pwm = seg.motor_pwm if seg.motor_pwm is not None else pwm
                    if dry_run:
                        lines.append(f"; [DRY RUN] M106 S{seg_pwm} (Motor Disabled)")
                    else:
                        lines.append(f"M106 S{seg_pwm} ; Dispenser Motor ON (PWM {seg_pwm})")

                    # Pre-dispense dwell if configured
                    pre_dwell = seg.dwell_ms if seg.dwell_ms > 0 else self.config.pre_dispense_dwell_ms
                    if pre_dwell > 0:
                        lines.append(f"G4 P{pre_dwell} ; Pre-dispense dwell {pre_dwell}ms")
                        stats.estimated_time_sec += (pre_dwell / 1000.0)

                # 3. Dispense moves (G1)
                seg_feed = seg.feedrate if seg.feedrate is not None else feed
                for pt in seg.points[1:]:
                    move_dist = current_pos.distance_to(pt)
                    stats.total_dispense_dist_mm += move_dist
                    stats.estimated_time_sec += (move_dist / (seg_feed / 60.0))

                    if current_feedrate != seg_feed:
                        lines.append(f"G1 X{pt.x:.{dec}f} Y{pt.y:.{dec}f} F{seg_feed:.1f}")
                        current_feedrate = seg_feed
                    else:
                        lines.append(f"G1 X{pt.x:.{dec}f} Y{pt.y:.{dec}f}")
                    
                    current_pos = Point2D(pt.x, pt.y)

                # 4. Turn off powder motor at end of segment
                if seg.is_dispense:
                    post_dwell = self.config.post_dispense_dwell_ms
                    if post_dwell > 0:
                        lines.append(f"G4 P{post_dwell} ; Post-dispense dwell {post_dwell}ms")
                        stats.estimated_time_sec += (post_dwell / 1000.0)
                    lines.append("M107 ; Dispenser Motor OFF")

            lines.append("")

        # Ending script
        lines.append("; --- Ending Sequence ---")
        for raw_line in self.config.ending_gcode.splitlines():
            s = raw_line.strip()
            if s:
                lines.append(s)

        stats.total_lines = len(lines)
        gcode_content = "\n".join(lines) + "\n"
        return gcode_content, stats
